### ISSUE TITLE
Api review

### ISSUE THREAD

**Issue by JelF** [0exp/qonfig#7]
# Config composition

It is nice and flexible feature, but multiple inheritance (when you compose multiple configs inside one setting / root) is not a good pattern.

I suggest to deprecate `compose` api untill gem widely used and make mount-style api instead. I.e.

```
class Config < Qonfig::DataSet
  setting :foo, :bar
  setting :baz, MyOtherConfig
  # or mount :baz, MyOtherConfig
  # or compose :baz, MyOtherConfig
end
```

# .freeze!

Use `::FrozenError` as superclas for `Qonfig::FrozenSettingsError` or remove `Qonfig::FrozenSettingsError`

**Comment by 0exp** [comment]
## .freeze!

`FrozenError`  introduced in `ruby 2.5`. `FrozenError` compatability can be achieved using the followed code:

```ruby
FrozenSettingsError = defined?(::FrozenError) ? Class.new(::FrozenError) : Class.new(Qonfig::Error) # catch all 
```

But i want to save a way to catch all `Qonfig::Error` errors :\ like `rescue Qonfig::Error`

**Comment by 0exp** [comment]
@JelF What is better? I am at crossroads

**Comment by 0exp** [comment]
## .freeze!
I think `Qonfig::FrozenSettingsError = Class.new(Qonfig::Error)` make sense because `Qonfig::DataSet` is a wrapper around `Qonfig::Settings` and all its behaviour 😕

**Comment by JelF** [comment]
> I think Qonfig::FrozenSettingsError = Class.new(Qonfig::Error) make sense (if you want to keep the way to capture all Qonfig-related errors) because Qonfig::DataSet is a wrapper around Qonfig::Settings and all its behaviour confused. This behaviour is chosen for ArgumentError error for example (Qonfig::ArgumetnError = Class.new(Qonfig::Error))

I never have seen any usage of theese superclasses

**Comment by JelF** [comment]
My idea is when people use `.freeze!` they are expecting config to be just frozen and act like frozen object (i.e. raise `FrozenError` sometimes)

**Comment by 0exp** [comment]
Yes, you are right. Then an implementation will be as follows:

```ruby
# ruby < 2.5 (older versions raises RuntimeErorr)
Qonfig::FrozenSettingsError = Class.new(::RuntimeError) 

# ruby >= 2.5
Qonfig::FrozenSettingsError = Class.new(::FrozenError)
```

**Comment by 0exp** [comment]
(mistakenly closed)

**Comment by 0exp** [comment]
`.compose` works in `Hash#merge` manner. I want to keep an ability to merge settings from the other config class to the root definitions. If you want to nest these settings - use a setting with nested definitions. This works correctly, intuitively, and this is the only way to do it semantically (it's a DSL to build your config definitions). `load_from_yaml`, `load_from_env`, `load_from_self` and etc works in this manner too: you should describe `nesting` manually by yourself.

---

We can reopen this issue later.

**Comment by 0exp** [comment]
At the moment, all nested definitions works only via `setting :any_key { ...nested_defintiions... }`
